### ISSUE TITLE
DynamicSurfacesDemo is missing nestedScrollingEnabled on ScrollView

### ISSUE THREAD

**Issue by koenvanderlinden** [udacity/ud862-samples#2] opened 2015-09-17 13:51 UTC
ScrollView in activity_main.xml is missing the android:nestedScrollingEnabled="true" property. So the image is not hidden during scrolling.

**Comment by jwill** [comment] 2016-04-27 04:32
Intended behavior. Committed the non-scrolling version.

**Closed as completed by jwill** 2016-04-27 04:32 UTC
